source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use Puma as the app server
gem 'puma', '~> 3.0'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors', require: 'rack/cors'

gem 'active_model_serializers', '~> 0.10.2'

gem 'devise'
gem 'rolify'
gem 'jsonapi'

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'mysql2', '~> 0.4.4'
  gem 'rspec-rails', '~> 3.5'
  gem 'factory_girl_rails'
  gem 'dotenv-rails'
end

group :development do
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem "rails-erd"
end

group :test do
  gem 'faker'
  gem 'shoulda', '~> 3.5'
  gem 'database_cleaner'
end

group :production do
  gem 'pg', '0.18.4'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'apipie-rails'
gem "kaminari"
